[primary]
primary-web ansible_host=3.238.32.144 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/local/bin/python3.9

[dr]
dr-web ansible_host=34.220.80.6 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/local/bin/python3.9

[webservers:children]
primary
dr

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
